services:
  frontend:
    build:
      context: ./front-end
      dockerfile: front.dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    environment:
      - NODE_OPTIONS=--max_old_space_size=4096
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./back-end
      dockerfile: back.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/remont_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=springuser
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: unless-stopped

  mysql:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=remont_db
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
      - mysql-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s 
      
    restart: unless-stopped

volumes:
  mysql-data: